import type { Metadata } from "next";
import { Nunito, Bricolage_Grotesque } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
// local components
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import ConditionalWrapper from "@/components/layout/conditional-wrapper";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

// Temporarily disable custom font to fix build issues
// const bricolageGrotesqueCondensed = localFont({
//   variable: "--font-bricolage-grotesque-condensed",
//   src: [
//     {
//       path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-ExtraLight.woff2",
//       weight: "200",
//       style: "normal",
//     },
//     // ... other font weights
//   ],
// });

export const metadata: Metadata = {
  title: "Tasty Fruit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${bricolageGrotesque.variable} antialiased flex flex-col min-h-screen`}
        suppressHydrationWarning={true}
      >
        {/* Header - Fixed positioning handled internally */}
        <Header />

        {/* Main Content Area with conditional wrapper */}
        <ConditionalWrapper>{children}</ConditionalWrapper>

        {/* Footer - Sticky to bottom */}
        <Footer />
      </body>
    </html>
  );
}
